# Generated by Django 4.0.4 on 2022-05-12 00:52

from django.db import migrations
from django.db import models

from accounts.models import Language

def populate_languages(apps, schemaeditor):
    languages = [
            {
                "key": "EN",
                "name": "English"
            },
            {
                "key": "ES",
                "name": "Espanol"
            },
            {
                "key": "DE",
                "name": "Deutsch"
            },
            {
                "key": "PT",
                "name": "Portugues"
            }
        ]
    Language = apps.get_model('accounts', 'Language')    
    for language in languages:
        lang_obj =Language(key=language.get("key"),
        name=language.get("name")
        )
    lang_obj.save()    



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_language_customuser_preffered_language'),
    ]

    operations = [
        migrations.RunPython(populate_languages)
    ]

